---
chdir: /home/cristian/pr0n/northpole.ro
environment: development
address: 0.0.0.0
port: 3000
timeout: 30
log: log/thin.log
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
daemonize: false
database_name: np
database_host: 127.0.0.1
database_port: 27017
